# Training Based on Twitter Sentiment Dataset

In [1]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import warnings
warnings.filterwarnings('ignore')
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vides\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\vides\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\vides\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [2]:
## Training Data
df=pd.read_csv("twitter.csv",header=None,names=['Slno','Category','Sentiment','Text'])

In [3]:
df.head()

,Slno,Category,Sentiment,Text
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 74682 entries, 0 to 74681
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Slno       74682 non-null  int64
 1   Category   74682 non-null  str
 2   Sentiment  74682 non-null  str
 3   Text       73996 non-null  str
dtypes: int64(1), str(3)
memory usage: 2.3 MB

In [5]:
df.shape

(74682, 4)

In [6]:
df.dropna(inplace=True)

In [7]:
df.drop('Category',axis=1,inplace=True)

In [8]:
df

       Slno Sentiment                                               Text
0      2401  Positive  im getting on borderlands and i will murder yo...
1      2401  Positive  I am coming to the borders and I will kill you...
2      2401  Positive  im getting on borderlands and i will kill you ...
3      2401  Positive  im coming on borderlands and i will murder you...
4      2401  Positive  im getting on borderlands 2 and i will murder ...
...     ...       ...                                                ...
74677  9200  Positive  Just realized that the Windows partition of my...
74678  9200  Positive  Just realized that my Mac window partition is ...
74679  9200  Positive  Just realized the windows partition of my Mac ...
74680  9200  Positive  Just realized between the windows partition of...
74681  9200  Positive  Just like the windows partition of my Mac is l...

[73996 rows x 3 columns]

In [9]:
df.loc[1]['Text']

'I am coming to the borders and I will kill you all,'

# Preprocessing Section

In [10]:
import string
def preprocess(text):
    if not isinstance(text, str):
        return ""
    if not text or text.strip()=="":
        return ""
    text=text.lower()
    text=text.translate(str.maketrans('','',string.punctuation))
    stop_words=set(stopwords.words('english'))
    lst=text.split()
    words=[word for word in lst if word not in stop_words]
    words1=[word for word in words if not word.startswith(("http://", "https://", "www."))]
    tokens=word_tokenize(" ".join(words1))
    new=""
    for i in tokens:
        if i.isalpha():
            new=new+i+" "
    new=new.strip()
    return new

In [11]:
df['Text']=df['Text'].apply(preprocess)

In [12]:
df.loc[1]['Text']

'coming borders kill'

# Vectorizing

In [13]:
## Bag Of Words
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()
X_train=vectorizer.fit_transform(df['Text'])
from sklearn.preprocessing import LabelEncoder
le_bow=LabelEncoder()
y_train=le_bow.fit_transform(df['Sentiment'])

In [14]:
## TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer1 = TfidfVectorizer()
X_train1 = vectorizer1.fit_transform(df['Text'])
from sklearn.preprocessing import LabelEncoder
le_tf=LabelEncoder()
y_train1=le_tf.fit_transform(df['Sentiment'])

# Creating Models based on Test Data (Bag of Words)

In [15]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
ModelLogisticBOW=LogisticRegression()
ModelLogisticBOW.fit(X_train,y_train)

LogisticRegression()

In [16]:
# NaiveBayas
from sklearn.naive_bayes import MultinomialNB
ModelNaiveBOW=MultinomialNB()
ModelNaiveBOW.fit(X_train,y_train)

MultinomialNB()

In [17]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier
modelTreeBOW=DecisionTreeClassifier()
modelTreeBOW.fit(X_train,y_train)

DecisionTreeClassifier()

# Creating Models based on TFIDF Vectorization

In [18]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
ModelLogisticTF=LogisticRegression()
ModelLogisticTF.fit(X_train1,y_train1)

LogisticRegression()

In [19]:
# Naive Bayas
from sklearn.naive_bayes import MultinomialNB
ModelNaiveTF=MultinomialNB()
ModelNaiveTF.fit(X_train1,y_train1)

MultinomialNB()

In [20]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier
modelTreeTF=DecisionTreeClassifier()
modelTreeTF.fit(X_train1,y_train1)

DecisionTreeClassifier()

# Importing Test Data

In [21]:
df1=pd.read_csv("twitter_validation.csv",header=None,names=['Slno','Company','Sentiment','Text'])

In [22]:
df1.head()

,Slno,Company,Sentiment,Text
0,3364,Facebook,Irrelevant,I mentioned on Facebook that I was struggling ...
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...

In [23]:
df1.drop(['Slno','Company'],axis=1,inplace=True)

In [24]:
df1['Text']=df1['Text'].apply(preprocess)
# Bag of Words
X_test=vectorizer.transform(df1['Text'])
y_test=le_bow.transform(df1['Sentiment'])

In [25]:
#TFIDF
X_test1=vectorizer1.transform(df1['Text'])
y_test1=le_tf.transform(df1['Sentiment'])

## Prediction of all Models based on Bag of Words

In [26]:
y_pred=ModelLogisticBOW.predict(X_test)
from sklearn.metrics import classification_report
print("Logistic Regression:")
print(classification_report(y_test, y_pred))

y_pred = ModelNaiveBOW.predict(X_test)
print("Naive Bayes:")
print(classification_report(y_test, y_pred))

y_pred = modelTreeBOW.predict(X_test)
print("Decision Tree:")
print(classification_report(y_test, y_pred))

Logistic Regression:
              precision    recall  f1-score   support

           0       0.94      0.90      0.92       172
           1       0.93      0.95      0.94       266
           2       0.95      0.92      0.94       285
           3       0.92      0.95      0.93       277

    accuracy                           0.93      1000
   macro avg       0.93      0.93      0.93      1000
weighted avg       0.93      0.93      0.93      1000

Naive Bayes:
              precision    recall  f1-score   support

           0       0.87      0.72      0.79       172
           1       0.77      0.89      0.82       266
           2       0.90      0.73      0.81       285
           3       0.78      0.88      0.83       277

    accuracy                           0.82      1000
   macro avg       0.83      0.81      0.81      1000
weighted avg       0.83      0.82      0.81      1000

Decision Tree:
              precision    recall  f1-score   support

           0       0.93      0.92      0.92       172
           1       0.93      0.95      0.94       266
           2       0.95      0.93      0.94       285
           3       0.93      0.94      0.93       277

    accuracy                           0.94      1000
   macro avg       0.94      0.93      0.93      1000
weighted avg       0.94      0.94      0.94      1000

In [27]:
y_pred=ModelLogisticTF.predict(X_test1)
from sklearn.metrics import classification_report
print("Logistic Regression:")
print(classification_report(y_test1, y_pred))

y_pred = ModelNaiveTF.predict(X_test1)
print("Naive Bayes:")
print(classification_report(y_test1, y_pred))

y_pred = modelTreeTF.predict(X_test1)
print("Decision Tree:")
print(classification_report(y_test1, y_pred))

Logistic Regression:
              precision    recall  f1-score   support

           0       0.91      0.88      0.89       172
           1       0.85      0.94      0.89       266
           2       0.94      0.85      0.90       285
           3       0.91      0.92      0.91       277

    accuracy                           0.90      1000
   macro avg       0.90      0.90      0.90      1000
weighted avg       0.90      0.90      0.90      1000

Naive Bayes:
              precision    recall  f1-score   support

           0       0.97      0.60      0.75       172
           1       0.69      0.94      0.80       266
           2       0.91      0.67      0.78       285
           3       0.77      0.90      0.83       277

    accuracy                           0.79      1000
   macro avg       0.84      0.78      0.79      1000
weighted avg       0.82      0.79      0.79      1000

Decision Tree:
              precision    recall  f1-score   support

           0       0.92      0.91      0.92       172
           1       0.93      0.94      0.93       266
           2       0.93      0.90      0.91       285
           3       0.92      0.94      0.93       277

    accuracy                           0.92      1000
   macro avg       0.92      0.92      0.92      1000
weighted avg       0.92      0.92      0.92      1000

In [28]:
data = {
    'Model': ['Logistic Regression', 'Naive Bayes', 'Decision Tree'],
    'BOW Accuracy': [0.93, 0.82, 0.94],
    'TF-IDF Accuracy': [0.90, 0.79, 0.92]}
df=pd.DataFrame(data)

In [29]:
df

                 Model  BOW Accuracy  TF-IDF Accuracy
0  Logistic Regression          0.93             0.90
1          Naive Bayes          0.82             0.79
2        Decision Tree          0.94             0.92

# Insights

#### 1. BOW outperforms TF-IDF across all models
Every model performed better with BOW than TF-IDF. This suggests that for Twitter sentiment data, raw word frequency matters more than weighted importance.

#### 2. Decision Tree is the best overall model

#### 3. Naive Bayes is the weakest model